title: CNTRL
subtitle: The official blog for cntr1.
description: CNTRL is an independent media focusing on style, culture, and creative expression.
blog_button:
  title: Blog
  description: Visit blog

