# Basic
title: CNTR1
subtitle: The official blog for cntr1.
# welcome_message: <a href="https://github.com/zhao-lingfeng/cntr1_website" target="_blank">Download the theme</a>
description: cntr1 is an independent media focusing on<br> style, culture, and creative expression.
creator: <a href="https://github.com/zhao-lingfeng">@zhao-lingfeng</a>

url: "https://cntr1.com"
baseurl: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'https://zhao-lingfeng.github.io/cntr1_website/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    instagram_official: https://www.instagram.com/cntr1_official/
    instagram_jp: https://www.instagram.com/cntr1_jp/
    mail: cntr1526@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
